In [8]:
import pandas as pd
import string
import math 
import numpy as np 
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
pd.set_option('display.max_colwidth', 0)
df = pd.read_csv("publications_data.csv")
df.head()

name                        job_title  \
0  Mohamad Nazri Abd Karim  Lecturer in Finance               
1  Muhammad Abdullah        Lecturer in Finance               
2  Al-Noor Abdullah         Lecturer in Business Management   
3  Al-Noor Abdullah         Lecturer in Business Management   
4  Mohamad Nazri Abd Karim  Lecturer in Finance               

                                  organization  \
0  School of Economics, Finance and Accounting   
1  School of Economics, Finance and Accounting   
2  School of Strategy and Leadership             
3  School of Strategy and Leadership             
4  School of Economics, Finance and Accounting   

                                                                                                              doc_link  \
0  https://pureportal.coventry.ac.uk/en/publications/stock-price-and-volume-effects-associated-with-changes-in-the-com   
1  https://pureportal.coventry.ac.uk/en/publications/assessing-the-use-of-gold-as-a-zero-beta-asset-in-empirical-asset   
2  https://pureportal.coventry.ac.uk/en/publications/social-impacts-of-a-mega-dam-project-as-perceived-by-local-resett   
3  https://pureportal.coventry.ac.uk/en/publications/economic-contributions-of-mega-dam-infrastructure-as-perceived-by   
4  https://pureportal.coventry.ac.uk/en/publications/personalisation-of-power-neoliberalism-and-the-production-of-corr   

                                                                                                                              doc_title  \
0  Stock Price and Volume Effects Associated with Changes in the Composition of the FTSE Bursa Malaysian KLCI                             
1  Assessing the Use of Gold as a Zero-Beta Asset in Empirical Asset Pricing: Application to the US Equity Market                         
2  Social Impacts of a Mega-Dam Project as Perceived by Local, Resettled and Displaced Communities: A Case Study of Merowe Dam, Sudan     
3  Economic Contributions of Mega-Dam Infrastructure as Perceived by Local and Displaced Communities: A Case Study of Merowe Dam, Sudan   
4  Personalisation of power, neoliberalism and the production of corruption                                                               

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              doc_abstract  
0

In [10]:
df['doc_content'] = df['name']+ ' ' + df['doc_title'] +" "+ df['doc_abstract']
df.head()

name                        job_title  \
0  Mohamad Nazri Abd Karim  Lecturer in Finance               
1  Muhammad Abdullah        Lecturer in Finance               
2  Al-Noor Abdullah         Lecturer in Business Management   
3  Al-Noor Abdullah         Lecturer in Business Management   
4  Mohamad Nazri Abd Karim  Lecturer in Finance               

                                  organization  \
0  School of Economics, Finance and Accounting   
1  School of Economics, Finance and Accounting   
2  School of Strategy and Leadership             
3  School of Strategy and Leadership             
4  School of Economics, Finance and Accounting   

                                                                                                              doc_link  \
0  https://pureportal.coventry.ac.uk/en/publications/stock-price-and-volume-effects-associated-with-changes-in-the-com   
1  https://pureportal.coventry.ac.uk/en/publications/assessing-the-use-of-gold-as-a-zero-beta-asset-in-empirical-asset   
2  https://pureportal.coventry.ac.uk/en/publications/social-impacts-of-a-mega-dam-project-as-perceived-by-local-resett   
3  https://pureportal.coventry.ac.uk/en/publications/economic-contributions-of-mega-dam-infrastructure-as-perceived-by   
4  https://pureportal.coventry.ac.uk/en/publications/personalisation-of-power-neoliberalism-and-the-production-of-corr   

                                                                                                                              doc_title  \
0  Stock Price and Volume Effects Associated with Changes in the Composition of the FTSE Bursa Malaysian KLCI                             
1  Assessing the Use of Gold as a Zero-Beta Asset in Empirical Asset Pricing: Application to the US Equity Market                         
2  Social Impacts of a Mega-Dam Project as Perceived by Local, Resettled and Displaced Communities: A Case Study of Merowe Dam, Sudan     
3  Economic Contributions of Mega-Dam Infrastructure as Perceived by Local and Displaced Communities: A Case Study of Merowe Dam, Sudan   
4  Personalisation of power, neoliberalism and the production of corruption                                                               

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              doc_abstract  \


In [11]:
df = df.dropna()
one_word_titles = df[df['doc_title'].str.count('\s') == 0]['doc_title']
df = df[~df['doc_title'].isin(one_word_titles)]
df = df.reset_index()
df = df.drop(columns = 'index')

In [12]:
df_final = df.drop(columns = ['doc_content'])
df_final.head(10)

name                                         job_title  \
0  Mohamad Nazri Abd Karim  Lecturer in Finance                                
1  Muhammad Abdullah        Lecturer in Finance                                
2  Al-Noor Abdullah         Lecturer in Business Management                    
3  Al-Noor Abdullah         Lecturer in Business Management                    
4  Zahir Ahmad              Curriculum Lead (Associate Professor - Academic)   
5  Zahir Ahmad              Curriculum Lead (Associate Professor - Academic)   
6  Mohamed Abdelshafy       Assistant Professor Academic                       
7  Bilal Ahmad              Research Fellow                                    
8  Olubunmi Ajala           Lecturer                                           
9  Araz Agha                Assistant Professor (Academic)                     

                                         organization  \
0  School of Economics, Finance and Accounting          
1  School of Economics, Finance and Accounting          
2  School of Strategy and Leadership                    
3  School of Strategy and Leadership                    
4  School of Future Transport Engineering               
5  School of Future Transport Engineering               
6  School of Computing, Mathematics and Data Sciences   
7  Centre for Manufacturing and Materials               
8  School of Economics, Finance and Accounting          
9  School of Energy, Construction and Environment       

                                                                                                                doc_link  \
0  https://pureportal.coventry.ac.uk/en/publications/stock-price-and-volume-effects-associated-with-changes-in-the-com     
1  https://pureportal.coventry.ac.uk/en/publications/assessing-the-use-of-gold-as-a-zero-beta-asset-in-empirical-asset     
2  https://pureportal.coventry.ac.uk/en/publications/social-impacts-of-a-mega-dam-project-as-perceived-by-local-resett     
3  https://pureportal.coventry.ac.uk/en/publications/economic-contributions-of-mega-dam-infrastructure-as-perceived-by     
4  https://pureportal.coventry.ac.uk/en/publications/demonstration-of-a-multi-hop-underwater-visible-light-communicati     
5  https://pureportal.coventry.ac.uk/en/publications/design-of-a-visible-light-communication-system-for-deep-sea-diver-2   
6  https://pureportal.coventry.ac.uk/en/publications/an-active-attack-on-token-based-security-protocol                     
7  https://pureportal.coventry.ac.uk/en/publications/residual-stresses-in-ultrasonically-peened-fillet-welded-joints-2     
8  https://pureportal.coventry.ac.uk/en/publications/do-lockdown-and-testing-help-in-curbing-covid-19-transmission         
9  https://pureportal.coventry.ac.uk/en/publications/building-research-establishment-environmental-assessment-methodol     

                                                                                                                              doc_title  \
0  Stock Price and Volume Effects Associated with Changes in the Composition of the FTSE Bursa Malaysian KLCI                             
1  Assessing the Use of Gold as a Zero-Beta Asset in Empirical Asset Pricing: Application to the US Equity Market                         
2  Social Impacts of a Mega-Dam Project as Perceived by Local, Resettled and Displaced Communities: A Case Study of Merowe Dam, Sudan     
3  Economic Contributions of Mega-Dam Infrastructure as Perceived by Local and Displaced Communities: A Case Study of Merowe Dam, Sudan   
4  Demonstration of a multi-hop underwater visible light communication system                                                             
5  Design of a visible light communication system for deep sea divers based on analogue frequency modulation                              
6  An Active Attack on Token-Based Security Protocol                                                                                      
7  Residual Stresses in Ultrasonical

In [13]:
def clean_docs(i, doc):
    stops = stopwords.words('english')
    words = doc.split()

    final = []

    for word in words:
        word = word.lower()
        word = word.replace('-', ' ')
        if word not in stops:
            final.append(word)
        
    final = " ". join(final)
    final = final.translate(str.maketrans("", "", string.punctuation))
    df_final.loc[i, 'doc_content'] = final

In [14]:
for i in range(0, len(df)):
    data = df.loc[i, 'doc_content']
    clean_docs(i, data)

In [15]:
df_final[0:5]

name                                         job_title  \
0  Mohamad Nazri Abd Karim  Lecturer in Finance                                
1  Muhammad Abdullah        Lecturer in Finance                                
2  Al-Noor Abdullah         Lecturer in Business Management                    
3  Al-Noor Abdullah         Lecturer in Business Management                    
4  Zahir Ahmad              Curriculum Lead (Associate Professor - Academic)   

                                  organization  \
0  School of Economics, Finance and Accounting   
1  School of Economics, Finance and Accounting   
2  School of Strategy and Leadership             
3  School of Strategy and Leadership             
4  School of Future Transport Engineering        

                                                                                                              doc_link  \
0  https://pureportal.coventry.ac.uk/en/publications/stock-price-and-volume-effects-associated-with-changes-in-the-com   
1  https://pureportal.coventry.ac.uk/en/publications/assessing-the-use-of-gold-as-a-zero-beta-asset-in-empirical-asset   
2  https://pureportal.coventry.ac.uk/en/publications/social-impacts-of-a-mega-dam-project-as-perceived-by-local-resett   
3  https://pureportal.coventry.ac.uk/en/publications/economic-contributions-of-mega-dam-infrastructure-as-perceived-by   
4  https://pureportal.coventry.ac.uk/en/publications/demonstration-of-a-multi-hop-underwater-visible-light-communicati   

                                                                                                                              doc_title  \
0  Stock Price and Volume Effects Associated with Changes in the Composition of the FTSE Bursa Malaysian KLCI                             
1  Assessing the Use of Gold as a Zero-Beta Asset in Empirical Asset Pricing: Application to the US Equity Market                         
2  Social Impacts of a Mega-Dam Project as Perceived by Local, Resettled and Displaced Communities: A Case Study of Merowe Dam, Sudan     
3  Economic Contributions of Mega-Dam Infrastructure as Perceived by Local and Displaced Communities: A Case Study of Merowe Dam, Sudan   
4  Demonstration of a multi-hop underwater visible light communication system                                                             

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

Exporting clean final df for text processing purposes

In [17]:
df_final.to_csv('cleaned_data.csv', index=False)

In [9]:
documents = list(df_final['doc_content'])

In [10]:
count = 0
for i in range(0, len(documents)):
    count += len(documents[i].split())
    
print(count)

944520


In [11]:
vectorizer = TfidfVectorizer(lowercase = True)

tfidf_matrix = vectorizer.fit_transform(documents)
print(tfidf_matrix.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [12]:
print(type(tfidf_matrix), tfidf_matrix.shape)

<class 'scipy.sparse._csr.csr_matrix'> (8924, 48349)


In [13]:

def query_processor(query):
    stops = stopwords.words('english')
    words = query.split()

    final = []

    for word in words:
        word = word.lower()
        word = word.replace('-', ' ')
        if word not in stops:
            final.append(word)
        
    final = " ". join(final)
    final = final.translate(str.maketrans("", "", string.punctuation))
    return final

In [47]:
query = "covid death"
processed_query = query_processor(query)
#Transform the query using the fitted vectorizer
query_vector = vectorizer.transform([processed_query])

#Compute the cosine similarity
cosine_similarities = cosine_similarity(query_vector, tfidf_matrix)

#Find the most similar document, argsort() causes the max value's index to be at the last 
most_similar_doc_index = cosine_similarities.argsort()[0]
#converting most_similar_doc_index to a list so that the index values can be reversed (in descending order)
similar_index_list = list(most_similar_doc_index)
similar_index_list.reverse()

similarities = []
similarities_percentage = []
most_similar_doc = []
length = int(len(similar_index_list)/(0.1*len(similar_index_list)))

for index in similar_index_list[0:10]:
    similarities.append(cosine_similarities[0][index])
    most_similar_doc.append(documents[index])

for s in similarities:
    similarities_percentage.append((s + 1) / 2 * 100)
   
print("Most similar document: \n", most_similar_doc[0])

Most similar document: 
 jonathan jong religious correlates death anxiety systematic review meta analysis various theories religion hypothesize connection death anxiety religiosity particular terror management theory’s worldview defense hypothesis predicts death anxiety lowest among religious irreligious individuals highest among uncertain individuals likewise supposition death anxiety motivates religious belief turn mitigates death anxiety predicts religiosity increases death anxiety among nonbelievers death anxiety decreases religiosity increases among believers cases curvilinear relationship—specifically inverted u curve—is predicted extracted 202 effect sizes 100 studies “omnibus” religiosity meta analysis six meta analyses examine particular dimensions religiosity found high heterogeneity weak negative association death anxiety religiosity closer examination revealed 10 11 studies directly tested curvilinearity provided support inverted u pattern curvilinearity hypothesis cannot r

In [48]:
most_similar_doc_index

array([   0, 5922, 5920, ..., 3811, 2937, 5160], dtype=int64)

In [49]:
len(most_similar_doc)

10

In [50]:
final_result = []

In [51]:
for i in range(0, len(most_similar_doc)):
    result = df_final.loc[similar_index_list[i]]
#     print(f"Similarity: {similarities[i]}\nS. Percentage: {similarities_percentage[i]:.2f}%\nAuthor: {result['name']}\nDocument Link: {result['doc_link']}")
#     print()
#     print(f"{result['doc_title']}")
#     print()
#     print(f"{result['doc_abstract']}")
#     print("~"*100)
    final_result.append({"Similarity": similarities[i],
                         "Similarity Percentage" : similarities_percentage[i],
                            "Author": result['name'],
                            "Document Link": result['doc_link'],
                            "Title" : result['doc_title'],
                            "Abstract" : result['doc_abstract']
                            })

In [52]:
final_result[0:4]

[{'Similarity': 0.32723440274926946,
  'Similarity Percentage': 66.36172013746348,
  'Author': 'Jonathan Jong',
  'Document Link': 'https://pureportal.coventry.ac.uk/en/publications/the-religious-correlates-of-death-anxiety-a-systematic-review-and-2',
  'Title': 'The religious correlates of death anxiety: A systematic review and meta-analysis',
  'Abstract': 'Various theories of religion hypothesize a connection between death anxiety and religiosity. In particular, Terror Management Theory’s worldview defense hypothesis predicts that death anxiety is lowest among very religious and irreligious individuals, and highest among uncertain individuals. Likewise, the supposition that death anxiety motivates religious belief, which in turn mitigates death anxiety predicts that religiosity increases with death anxiety among nonbelievers, and that death anxiety decreases as religiosity increases among believers. In both cases, a curvilinear relationship—specifically, an inverted-U curve—is predi